import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
//import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import InformationBox from '@/components/InfoBox'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_.png" />
      </Head>
      <div>
        <InformationBox/>
        <h2>메인페이지</h2>
        <Link href = "/login" ><span className='hover:text-red-700 '> 로그인 </span></Link>
        <Link href = "/join"> 회원가입 </Link>
      </div>
    </>
  )
}
